import { LanguageString } from '../models';

export interface Leader {
  name: LanguageString;
  type: 'old' | 'new';
  house: LanguageString;
  passiveName: LanguageString;
  passiveDescription: LanguageString;
  signetName: LanguageString;
  signetDescription: LanguageString;
  imageUrl: string;
}

export const leaders: Leader[] = [
  {
    name: { de: 'stilgar', en: 'stilgar' },
    house: { de: 'fremen', en: 'fremen' },
    passiveName: { de: 'naib', en: 'naib' },
    passiveDescription: { de: 'Du hast Zugang zu Sietch Tabr.', en: 'You can access sietch tabr.' },
    signetName: { de: 'die wege der fremen', en: 'the fremen ways' },
    signetDescription: {
      de: 'Ziehe eine verdeckte Intrige. Du kannst sie jederzeit entsorgen um {resource:troops} und sie in den Kampf zu schicken.',
      en: 'Draw an intrigue face down. You may trash it at any time to {resource:troops} and put it into combat.',
    },
    type: 'new',
    imageUrl: '/assets/images/leaders/stilgar.png',
  },
  {
    name: { de: 'liet lynes', en: 'liet lynes' },
    house: { de: 'fremen', en: 'fremen' },
    passiveName: { de: 'anführer der fremen', en: 'leader of the fremen' },
    passiveDescription: {
      de: 'Du beginnst das Spiel mit dem maximalen Einfluss bei den Fremen. Jedes Mal, wenn ein Gegner Fremen-Einfluss gewinnt, verlierst du 1.',
      en: 'You start with the maximum fremen influence. Every time an opponent gains fremen influence, you lose 1.',
    },
    signetName: { de: 'pflanzen des paradieses', en: 'planting the paradise' },
    signetDescription: {
      de: '{resource:water}{resource:water}{resource:water} -> {resource:victory-point}',
      en: '{resource:water}{resource:water}{resource:water} -> {resource:victory-point}',
    },
    type: 'new',
    imageUrl: '/assets/images/leaders/liet.png',
  },
  {
    name: { de: 'chani kynes', en: 'chani kynes' },
    house: { de: 'fremen', en: 'fremen' },
    passiveName: { de: 'sayyadina', en: 'sayyadina' },
    passiveDescription: {
      de: 'Du kannst Fremen-Karten für 1 Überzeugung weniger kaufen.',
      en: 'Fremen cards cost 1 less persuasion to buy.',
    },
    signetName: { de: 'kind der wüste', en: 'child of the desert' },
    signetDescription: {
      de: 'Der Zugang zu einem Agentenfeld kostet {resource:water} weniger.',
      en: 'Accessing an agent space costs {resource:water} less.',
    },
    type: 'new',
    imageUrl: '/assets/images/leaders/chani.png',
  },
  {
    name: { de: 'alia atreides', en: 'alia atreides' },
    house: { de: 'haus atreides', en: 'house atreides' },
    passiveName: { de: 'vorgeboren', en: 'pre-born' },
    passiveDescription: {
      de: '{resource:card-round-start}. Du kannst deinen Siegelring nicht entsorgen. Jedes Mal, wenn du ihn aufdeckst, verlierst du {resource:victory-point}.',
      en: '{resource:card-round-start}. You cannot trash your signet ring. Every time you reveal it, you lose {resource:victory-point}.',
    },
    signetName: { de: 'ego-erinnerungen', en: 'ego-memories' },
    signetDescription: {
      de: '{resource:card-discard} {resource:card-destroy}',
      en: '{resource:card-discard} {resource:card-destroy}',
    },
    type: 'new',
    imageUrl: '/assets/images/leaders/alia.png',
  },
  {
    name: { de: 'der prediger', en: 'the preacher' },
    house: { de: '-', en: '-' },
    passiveName: { de: 'blind und doch sehend', en: 'blind but seeing' },
    passiveDescription: {
      de: 'Einmal pro Runde darfst du 1 Karte aus dem Spiel zurück auf deine Hand nehmen.',
      en: 'Once each round, you may add 1 card in play back to your hand.',
    },
    signetName: { de: 'anklagender prophet', en: 'accusing prophet' },
    signetDescription: {
      de: 'Jeder Spieler {resource:card-discard}.',
      en: 'Every player {resource:card-discard}.',
    },
    type: 'new',
    imageUrl: '/assets/images/leaders/preacher.png',
  },
  {
    name: { de: 'prinzessin irulan corrino', en: 'princess irulan corrino' },
    house: { de: 'haus corrino', en: 'house corrino' },
    passiveName: { de: 'tochter des imperators', en: 'daughter of the emperor' },
    passiveDescription: {
      de: 'Entferne deinen Marker von Imperator-Einflussleiste. Jedes Mal, wenn du Imperator-Einfluss erhalten würdest, erhältst du {resource:currency}.',
      en: 'Remove your marker from the emperor track. Every time you would gain emperor influence, get {resource:currency}.',
    },
    signetName: { de: 'chronistin', en: 'chronicler' },
    signetDescription: {
      de: 'Ziehe eine verdeckte Intrige. Du kannst sie jederzeit entsorgen um {resource:card-draw}{resource:card-draw}.',
      en: 'Draw an intrigue face down. You may trash it at any time to {resource:card-draw}{resource:card-draw}.',
    },
    type: 'new',
    imageUrl: '/assets/images/leaders/irulan.png',
  },
  {
    name: { de: 'feyd-rautha harkonnen', en: 'feyd-rautha harkonnen' },
    house: { de: 'haus harkonnen', en: 'house harkonnen' },
    passiveName: { de: 'rücksichtsloser ehrgeiz', en: 'ruthless ambition' },
    passiveDescription: {
      de: 'Spiele mit allen deinen Intrigen aufgedeckt. Jedes Mal, wenn du eine Intrige ziehst, ziehe stattdessen 2 und entsorge dann eine davon weg.',
      en: 'Play with all your intrigues revealed. Every time you would draw an intrigue, draw 2 instead, then trash one of them.',
    },
    signetName: { de: 'verstecktes gift', en: 'hidden poison' },
    signetDescription: {
      de: 'Ziehe eine verdeckte Intrige. Du kannst sie jederzeit entsorgen, um 1 gegnerische Truppe im Kampf zu vernichten.',
      en: 'Draw an intrigue face down. You may trash it at any time to destroy 1 enemy troop in combat.',
    },
    type: 'new',
    imageUrl: '/assets/images/leaders/feyd.png',
  },
  {
    name: { de: 'graf hasimir fenring', en: 'count hasimir fenring' },
    house: { de: 'haus fenring', en: 'house fenring' },
    passiveName: { de: 'politischer taktiker', en: 'political tactician' },
    passiveDescription: {
      de: 'Du beginnst mit {resource:foldspace}{resource:foldspace} in deinem Deck.',
      en: 'You begin with {resource:foldspace}{resource:foldspace} in your deck.',
    },
    signetName: { de: 'vorgetäuschte schwäche', en: 'feigned weakness' },
    signetDescription: {
      de: 'Du kannst {resource:card-discard}. Wenn du das tust, füge du an deinem Aufdeckzug entweder 3 Kampfstärke hinzu oder {resource:card-draw}{resource:card-destroy}.',
      en: 'You may {resource:card-discard}. If you do, at your reveal turn, either add 3 combat power or {resource:card-draw}{resource:card-destroy}.',
    },
    type: 'new',
    imageUrl: '/assets/images/leaders/hasimir.png',
  },
  {
    name: { de: 'lady margot fenring', en: 'lady margot fenring' },
    house: { de: 'haus fenring', en: 'house fenring' },
    passiveName: { de: 'bene gesserit training', en: 'bene gesserit training' },
    passiveDescription: {
      de: 'Einmal pro Runde kannst du einen Spieler dazu zwingen, eine Intrige aufzudecken (nicht auszuspielen).',
      en: 'Once every round, you may force a player to reveal (not play) an intrigue.',
    },
    signetName: { de: 'hypnotische verführung', en: 'hypnotic seduction' },
    signetDescription: {
      de: 'Entferne eine Karte aus der Imperiumsreihe. In dieser Runde kannst du diese Karte für 2 weniger Überzeugung erwerben.',
      en: 'Remove a card from the imperium row. This round, you can buy this card for 2 less persuasion.',
    },
    type: 'new',
    imageUrl: '/assets/images/leaders/margot.png',
  },
  {
    name: { de: 'paul atreides', en: 'paul atreides' },
    type: 'old',
    house: { de: '', en: '' },
    passiveName: { de: '', en: '' },
    passiveDescription: { de: '', en: '' },
    signetName: { de: '', en: '' },
    signetDescription: { de: '', en: '' },
    imageUrl: '/assets/images/leaders/old/paul.jpg',
  },
  {
    name: { de: 'herzog leto atreides', en: 'duke leto atreides' },
    type: 'old',
    house: { de: '', en: '' },
    passiveName: { de: '', en: '' },
    passiveDescription: { de: '', en: '' },
    signetName: { de: '', en: '' },
    signetDescription: { de: '', en: '' },
    imageUrl: '/assets/images/leaders/old/leto.jpg',
  },
  {
    name: { de: 'graf ilban richese', en: 'count ilban richese' },
    type: 'old',
    house: { de: '', en: '' },
    passiveName: { de: '', en: '' },
    passiveDescription: { de: '', en: '' },
    signetName: { de: '', en: '' },
    signetDescription: { de: '', en: '' },
    imageUrl: '/assets/images/leaders/old/ilban.jpg',
  },
  {
    name: { de: 'helena richese', en: 'helena richese' },
    type: 'old',
    house: { de: '', en: '' },
    passiveName: { de: '', en: '' },
    passiveDescription: { de: '', en: '' },
    signetName: { de: '', en: '' },
    signetDescription: { de: '', en: '' },
    imageUrl: '/assets/images/leaders/old/helena.jpg',
  },
  {
    name: { de: 'baron vladimir harkonnen', en: 'baron vladimir harkonnen' },
    type: 'old',
    house: { de: '', en: '' },
    passiveName: { de: '', en: '' },
    passiveDescription: { de: '', en: '' },
    signetName: { de: '', en: '' },
    signetDescription: { de: '', en: '' },
    imageUrl: '/assets/images/leaders/old/vlad.jpg',
  },
  {
    name: { de: 'glossu "die bestie" rabban', en: 'glossu "the beast" rabban' },
    type: 'old',
    house: { de: '', en: '' },
    passiveName: { de: '', en: '' },
    passiveDescription: { de: '', en: '' },
    signetName: { de: '', en: '' },
    signetDescription: { de: '', en: '' },
    imageUrl: '/assets/images/leaders/old/rabban.jpg',
  },
  {
    name: { de: 'gräfin ariana thorvald', en: 'countess ariana thorvald' },
    type: 'old',
    house: { de: '', en: '' },
    passiveName: { de: '', en: '' },
    passiveDescription: { de: '', en: '' },
    signetName: { de: '', en: '' },
    signetDescription: { de: '', en: '' },
    imageUrl: '/assets/images/leaders/old/ariana.jpg',
  },
  {
    name: { de: 'graf memnon thorvald', en: 'count memnon thorvald' },
    type: 'old',
    house: { de: '', en: '' },
    passiveName: { de: '', en: '' },
    passiveDescription: { de: '', en: '' },
    signetName: { de: '', en: '' },
    signetDescription: { de: '', en: '' },
    imageUrl: '/assets/images/leaders/old/memnon.jpg',
  },
  // {
  //   name: 'count hundro moritani',
  //   type: 'old',
  //   house: '',
  //   passiveName: '?',
  //   passiveDescription: ' ',
  //   signetName: '?',
  //   signetDescription: ' ',
  //   imageUrl: '/assets/images/leaders/old/hundro.jpg',
  // },
  {
    name: { de: '"prinzessin" yuna moritani', en: '"princess" yuna moritani' },
    type: 'old',
    house: { de: '', en: '' },
    passiveName: { de: '', en: '' },
    passiveDescription: { de: '', en: '' },
    signetName: { de: '', en: '' },
    signetDescription: { de: '', en: '' },
    imageUrl: '/assets/images/leaders/old/yuna.jpg',
  },
  {
    name: { de: 'erzherzog  armand ecaz', en: 'archduke armand ecaz' },
    type: 'old',
    house: { de: '', en: '' },
    passiveName: { de: '', en: '' },
    passiveDescription: { de: '', en: '' },
    signetName: { de: '', en: '' },
    signetDescription: { de: '', en: '' },
    imageUrl: '/assets/images/leaders/old/armand.jpg',
  },
  // {
  //   name: 'ilesa ecaz',
  //   type: 'old',
  //   house: '',
  //   passiveName: '?',
  //   passiveDescription: ' ',
  //   signetName: '?',
  //   signetDescription: ' ',
  //   imageUrl: '/assets/images/leaders/old/ilesa.jpg',
  // },
  {
    name: { de: 'tessia vernius', en: 'tessia vernius' },
    type: 'new',
    house: { de: 'haus vernius', en: 'house vernius' },
    passiveName: { de: 'ixianische geschenke', en: 'ixian gifts' },
    passiveDescription: {
      de: 'An deinem Aufdeckzug kannst du 2 tech-plättchen entsorgen, um {resource:victory-point} zu erhalten.',
      en: 'At your reveal turn, you may trash 2 tech tiles to get {resource:victory-point}.',
    },
    signetName: { de: 'inspirierende präsenz', en: 'inspiring presence' },
    signetDescription: {
      de: 'Du kannst den Effekt der im nächsten Zug von dir ausgespielten Karte doppelt aktivieren.',
      en: 'You can activate the effect of the card you played next turn twice.',
    },
    imageUrl: '/assets/images/leaders/tessia.png',
  },
  {
    name: { de: 'graf rhombur vernius', en: 'earl rhombur vernius' },
    type: 'new',
    house: { de: 'haus vernius', en: 'house vernius' },
    passiveName: { de: 'graf von ix', en: 'earl of ix' },
    passiveDescription: {
      de: 'An deinem Aufdeckzug kannst du {resource:tech}.',
      en: 'At your reveal turn, you may {resource:tech}.',
    },
    signetName: { de: 'kybernetische erweiterungen', en: 'enhanced cybernetics' },
    signetDescription: {
      de: '{resource:card-discard} dann {resource:card-draw}.',
      en: '{resource:card-discard} then {resource:card-draw}.',
    },
    imageUrl: '/assets/images/leaders/rhombur.png',
  },
  {
    name: { de: 'graf august metulli', en: 'count august metulli' },
    type: 'new',
    house: { de: 'haus metulli', en: 'house metulli' },
    passiveName: { de: 'isolationist', en: 'isolationist' },
    passiveDescription: {
      de: 'An deinem Aufdeckzug kannst du keine Karten erwerben. Du kannst stattdessen {resource:conviction}{resource:conviction} -> {resource:currency}.',
      en: 'You cannot purchase cards on your reveal turn. You can instead {resource:conviction}{resource:conviction} -> {resource:currency}.',
    },
    signetName: { de: 'ansprache an das volk', en: 'address to the people' },
    signetDescription: {
      de: '{resource:conviction} und {resource:troops}.',
      en: '{resource:conviction} and {resource:troops}.',
    },
    imageUrl: '/assets/images/leaders/august.png',
  },
  {
    name: { de: 'lunara metulli', en: 'lunara metulli' },
    type: 'new',
    house: { de: 'haus metulli', en: 'house metulli' },
    passiveName: { de: 'untergehendes haus', en: 'declining house' },
    passiveDescription: {
      de: 'An deinem Aufdeckzug erhältst du nur die Hälfte deiner eigentlichen Überzeugung.',
      en: 'On your reveal turn, you only get half of your actual persuasion.',
    },
    signetName: { de: 'sorgfältiges vorgehen', en: 'thorough approach' },
    signetDescription: {
      de: 'Wenn du in diesem Zug {resource:currency}, {resource:spice} oder {resource:water} erhältst, erhältst von einer deiner Wahl 1 mehr.',
      en: 'If you get {resource:currency}, {resource:spice} or {resource:water} this turn, get 1 more of one of your choice.',
    },
    imageUrl: '/assets/images/leaders/lunara.png',
  },
];
